package GameApp;


/**
* GameApp/_GameImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed Systems Project/Game.idl
* Friday, 20 February 2015 14:40:55 o'clock GMT
*/

public abstract class _GameImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements GameApp.Game, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _GameImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("player1", new java.lang.Integer (0));
    _methods.put ("player2", new java.lang.Integer (1));
    _methods.put ("chooseNumber", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameApp/Game/player1
       {
         String $result = null;
         $result = this.player1 ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // GameApp/Game/player2
       {
         String $result = null;
         $result = this.player2 ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // GameApp/Game/chooseNumber
       {
         int option = in.read_long ();
         boolean $result = false;
         $result = this.chooseNumber (option);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameApp/Game:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _GameImplBase
