package GameApp;


/**
* GameApp/Game.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Wednesday, 25 February 2015 14:00:06 o'clock GMT
*/

public interface Game extends GameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Game
