package GameApp;


/**
* GameApp/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed Systems Project/Game.idl
* Friday, 20 February 2015 14:40:55 o'clock GMT
*/

public interface GameOperations 
{
  String player1 ();
  String player2 ();
  boolean chooseNumber (int option);
} // interface GameOperations
