package GameApp;


/**
* GameApp/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Wednesday, 25 February 2015 14:00:06 o'clock GMT
*/

public interface GameOperations 
{
  String player1 (String name1);
  String player2 (String name2);
  String register (String username);
  String chooseMove (String option);
  boolean playAgain (int choice);
} // interface GameOperations
