package GameApp;


/**
* GameApp/GamePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Wednesday, 25 February 2015 14:00:06 o'clock GMT
*/

public class GamePOATie extends GamePOA
{

  // Constructors

  public GamePOATie ( GameApp.GameOperations delegate ) {
      this._impl = delegate;
  }
  public GamePOATie ( GameApp.GameOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public GameApp.GameOperations _delegate() {
      return this._impl;
  }
  public void _delegate (GameApp.GameOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String player1 (String name1)
  {
    return _impl.player1(name1);
  } // player1

  public String player2 (String name2)
  {
    return _impl.player2(name2);
  } // player2

  public String register (String username)
  {
    return _impl.register(username);
  } // register

  public String chooseMove (String option)
  {
    return _impl.chooseMove(option);
  } // chooseMove

  public boolean playAgain (int choice)
  {
    return _impl.playAgain(choice);
  } // playAgain

  private GameApp.GameOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GamePOATie
