package GameApp;


/**
* GameApp/GamePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Wednesday, 25 February 2015 14:00:06 o'clock GMT
*/

public abstract class GamePOA extends org.omg.PortableServer.Servant
 implements GameApp.GameOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("player1", new java.lang.Integer (0));
    _methods.put ("player2", new java.lang.Integer (1));
    _methods.put ("register", new java.lang.Integer (2));
    _methods.put ("chooseMove", new java.lang.Integer (3));
    _methods.put ("playAgain", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameApp/Game/player1
       {
         String name1 = in.read_string ();
         String $result = null;
         $result = this.player1 (name1);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // GameApp/Game/player2
       {
         String name2 = in.read_string ();
         String $result = null;
         $result = this.player2 (name2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // GameApp/Game/register
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.register (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // GameApp/Game/chooseMove
       {
         String option = in.read_string ();
         String $result = null;
         $result = this.chooseMove (option);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // GameApp/Game/playAgain
       {
         int choice = in.read_long ();
         boolean $result = false;
         $result = this.playAgain (choice);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameApp/Game:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Game _this() 
  {
    return GameHelper.narrow(
    super._this_object());
  }

  public Game _this(org.omg.CORBA.ORB orb) 
  {
    return GameHelper.narrow(
    super._this_object(orb));
  }


} // class GamePOA
