package GameApp;


/**
* GameApp/GameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed Systems Project/Game.idl
* Friday, 20 February 2015 14:40:55 o'clock GMT
*/

abstract public class GameHelper
{
  private static String  _id = "IDL:GameApp/Game:1.0";

  public static void insert (org.omg.CORBA.Any a, GameApp.Game that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameApp.Game extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameApp.GameHelper.id (), "Game");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameApp.Game read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameApp.Game value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameApp.Game narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameApp.Game)
      return (GameApp.Game)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameApp._GameStub stub = new GameApp._GameStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameApp.Game unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameApp.Game)
      return (GameApp.Game)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameApp._GameStub stub = new GameApp._GameStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
