package GameApp;

/**
* GameApp/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Wednesday, 25 February 2015 14:00:06 o'clock GMT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (GameApp.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.GameHelper.type ();
  }

}
