package Game;


/**
* Game/_GameRoomStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Friday, 13 March 2015 14:01:51 o'clock GMT
*/

public class _GameRoomStub extends org.omg.CORBA.portable.ObjectImpl implements Game.GameRoom
{

  public void registerForGame (org.omg.CORBA.Any anyPlayerDetails, org.omg.CORBA.StringHolder password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerForGame", true);
                $out.write_any (anyPlayerDetails);
                $in = _invoke ($out);
                password.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerForGame (anyPlayerDetails, password        );
            } finally {
                _releaseReply ($in);
            }
  } // registerForGame

  public void game (String UniqueID, int choice)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("game", true);
                $out.write_string (UniqueID);
                $out.write_long (choice);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                game (UniqueID, choice        );
            } finally {
                _releaseReply ($in);
            }
  } // game

  public Game.playerDetails getPlayerInfo (String UniqueID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayerInfo", true);
                $out.write_string (UniqueID);
                $in = _invoke ($out);
                Game.playerDetails $result = Game.playerDetailsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayerInfo (UniqueID        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayerInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Game/GameRoom:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameRoomStub
