package Game;


/**
* Game/_GameRoomImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/Game.idl
* 13 March 2015 14:47:35 o'clock GMT
*/

public abstract class _GameRoomImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Game.GameRoom, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _GameRoomImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerForGame", new java.lang.Integer (0));
    _methods.put ("game", new java.lang.Integer (1));
    _methods.put ("getPlayerInfo", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Game/GameRoom/registerForGame
       {
         org.omg.CORBA.Any anyPlayerDetails = in.read_any ();
         org.omg.CORBA.StringHolder password = new org.omg.CORBA.StringHolder ();
         this.registerForGame (anyPlayerDetails, password);
         out = $rh.createReply();
         out.write_string (password.value);
         break;
       }

       case 1:  // Game/GameRoom/game
       {
         String UniqueID = in.read_string ();
         int choice = in.read_long ();
         this.game (UniqueID, choice);
         out = $rh.createReply();
         break;
       }

       case 2:  // Game/GameRoom/getPlayerInfo
       {
         String UniqueID = in.read_string ();
         Game.playerDetails $result = null;
         $result = this.getPlayerInfo (UniqueID);
         out = $rh.createReply();
         Game.playerDetailsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Game/GameRoom:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _GameRoomImplBase
