package Game;


/**
* Game/GameRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Friday, 13 March 2015 14:01:51 o'clock GMT
*/

public interface GameRoom extends GameRoomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameRoom
