package Game;


/**
* Game/GameRoom_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/GameRoom.idl
* 02 April 2015 14:11:57 o'clock IST
*/

public class GameRoom_Tie extends _GameRoomImplBase
{

  // Constructors
  public GameRoom_Tie ()
  {
  }

  public GameRoom_Tie (Game.GameRoomOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Game.Member m, String name)
  {
    _impl.registerCB(m, name);
  } // registerCB

  public void setChoice (Game.Member m, int choice)
  {
    _impl.setChoice(m, choice);
  } // setChoice

  private Game.GameRoomOperations _impl;

} // class GameRoom_Tie
