package Game;


/**
* Game/GameRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/GameRoom.idl
* 02 April 2015 14:11:57 o'clock IST
*/

public interface GameRoomOperations 
{
  void registerCB (Game.Member m, String name);
  void setChoice (Game.Member m, int choice);
} // interface GameRoomOperations
