package Game;


/**
* Game/GameRoomHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Friday, 13 March 2015 14:01:51 o'clock GMT
*/

abstract public class GameRoomHelper
{
  private static String  _id = "IDL:Game/GameRoom:1.0";

  public static void insert (org.omg.CORBA.Any a, Game.GameRoom that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Game.GameRoom extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Game.GameRoomHelper.id (), "GameRoom");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Game.GameRoom read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameRoomStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Game.GameRoom value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Game.GameRoom narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Game.GameRoom)
      return (Game.GameRoom)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Game._GameRoomStub stub = new Game._GameRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Game.GameRoom unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Game.GameRoom)
      return (Game.GameRoom)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Game._GameRoomStub stub = new Game._GameRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
