package Game;


/**
* Game/GameRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Friday, 13 March 2015 14:01:51 o'clock GMT
*/

public interface GameRoomOperations 
{
  void registerForGame (org.omg.CORBA.Any anyPlayerDetails, org.omg.CORBA.StringHolder password);
  void game (String UniqueID, int choice);
  Game.playerDetails getPlayerInfo (String UniqueID);
} // interface GameRoomOperations
