package Game;


/**
* Game/GameRoom_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Friday, 13 March 2015 14:01:51 o'clock GMT
*/

public class GameRoom_Tie extends _GameRoomImplBase
{

  // Constructors
  public GameRoom_Tie ()
  {
  }

  public GameRoom_Tie (Game.GameRoomOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerForGame (org.omg.CORBA.Any anyPlayerDetails, org.omg.CORBA.StringHolder password)
  {
    _impl.registerForGame(anyPlayerDetails, password);
  } // registerForGame

  public void game (String UniqueID, int choice)
  {
    _impl.game(UniqueID, choice);
  } // game

  public Game.playerDetails getPlayerInfo (String UniqueID)
  {
    return _impl.getPlayerInfo(UniqueID);
  } // getPlayerInfo

  private Game.GameRoomOperations _impl;

} // class GameRoom_Tie
