package Game;

/**
* Game/PlayerDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Tuesday, 10 March 2015 15:36:19 o'clock GMT
*/

public final class PlayerDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public Game.PlayerDetails value = null;

  public PlayerDetailsHolder ()
  {
  }

  public PlayerDetailsHolder (Game.PlayerDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Game.PlayerDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Game.PlayerDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Game.PlayerDetailsHelper.type ();
  }

}
