package Game;


/**
* Game/playerDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Friday, 13 March 2015 14:01:51 o'clock GMT
*/

public final class playerDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String playerName = null;
  public String UniqueID = null;

  public playerDetails ()
  {
  } // ctor

  public playerDetails (String _playerName, String _UniqueID)
  {
    playerName = _playerName;
    UniqueID = _UniqueID;
  } // ctor

} // class playerDetails
