package Game;


/**
* Game/PlayerDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Game.idl
* Tuesday, 10 March 2015 15:36:19 o'clock GMT
*/

public final class PlayerDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String PlayerName = null;
  public String UniqueID = null;

  public PlayerDetails ()
  {
  } // ctor

  public PlayerDetails (String _PlayerName, String _UniqueID)
  {
    PlayerName = _PlayerName;
    UniqueID = _UniqueID;
  } // ctor

} // class PlayerDetails
