package Game;

/**
* Game/playerDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/Game.idl
* 13 March 2015 14:47:35 o'clock GMT
*/

public final class playerDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public Game.playerDetails value = null;

  public playerDetailsHolder ()
  {
  }

  public playerDetailsHolder (Game.playerDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Game.playerDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Game.playerDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Game.playerDetailsHelper.type ();
  }

}
