// Game.idl
module Game
{
    interface Member
    {
        oneway void callBack(in string message);
    };
    
    interface GameRoom
    {
	oneway void registerCB(in Member m, in string name);
	oneway void setChoice(in Member m, in long choice);
    };
};
