// Game.idl
module Game
{
	struct playerDetails{
		string playerName;
		string UniqueID;
	};
		
    interface Member
    {
        oneway void callBack(in string message);
    };
    
    interface GameRoom
    {
	 void registerForGame(in any anyPlayerDetails, out string password);
	 void game(in string UniqueID, in long choice) ;
	 playerDetails getPlayerInfo(in string UniqueID);
    };
};
