// Game.idl
module Game
{
    interface Member
    {
        oneway void callBack(in string message);
    };
    
    interface GameRoom
    {
	oneway void registerCB(in Member m, in string name);
	oneway void chat(in string c, in string name) ;
    };
};
