package Chat;


/**
* Chat/_GameRoomImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:34:48 o'clock GMT
*/

public abstract class _GameRoomImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Chat.GameRoom, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _GameRoomImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerCB", new java.lang.Integer (0));
    _methods.put ("chat", new java.lang.Integer (1));
    _methods.put ("game", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Chat/GameRoom/registerCB
       {
         Chat.Member m = Chat.MemberHelper.read (in);
         String name = in.read_string ();
         this.registerCB (m, name);
         out = $rh.createReply();
         break;
       }

       case 1:  // Chat/GameRoom/chat
       {
         String c = in.read_string ();
         String name = in.read_string ();
         this.chat (c, name);
         out = $rh.createReply();
         break;
       }

       case 2:  // Chat/GameRoom/game
       {
         Chat.Member m = Chat.MemberHelper.read (in);
         this.game (m);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Chat/GameRoom:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _GameRoomImplBase
