package Chat;


/**
* Chat/ChatRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/Chatroom.idl
* 02 April 2015 10:41:01 o'clock IST
*/

public interface ChatRoom extends ChatRoomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatRoom
