package Chat;


/**
* Chat/ChatRoom_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:38:05 o'clock GMT
*/

public class ChatRoom_Tie extends _ChatRoomImplBase
{

  // Constructors
  public ChatRoom_Tie ()
  {
  }

  public ChatRoom_Tie (Chat.ChatRoomOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Chat.Member m, String name)
  {
    _impl.registerCB(m, name);
  } // registerCB

  public void chat (String c, String name)
  {
    _impl.chat(c, name);
  } // chat

  public void game (Chat.Member m)
  {
    _impl.game(m);
  } // game

  public void move (short option)
  {
    _impl.move(option);
  } // move

  private Chat.ChatRoomOperations _impl;

} // class ChatRoom_Tie
