package Chat;


/**
* Chat/ChatRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/Chatroom.idl
* 25 March 2015 21:11:18 o'clock GMT
*/

public interface ChatRoom extends ChatRoomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatRoom
