package Chat;


/**
* Chat/ChatRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Distributed-Systems-Project/Chatroom.idl
* 25 March 2015 21:11:18 o'clock GMT
*/

public interface ChatRoomOperations 
{
  void registerCB (Chat.Member m, String name);
  void chat (String c, String name);
} // interface ChatRoomOperations
