package Chat;


/**
* Chat/ChatRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Thursday, 26 March 2015 14:24:26 o'clock GMT
*/

public interface ChatRoomOperations 
{
  void registerCB (Chat.Member m, String name);
  void chat (String c, String name);
} // interface ChatRoomOperations
