package Chat;

/**
* Chat/ChatRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Tuesday, 31 March 2015 15:22:24 o'clock BST
*/

public final class ChatRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.ChatRoom value = null;

  public ChatRoomHolder ()
  {
  }

  public ChatRoomHolder (Chat.ChatRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.ChatRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.ChatRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.ChatRoomHelper.type ();
  }

}
