package Chat;


/**
* Chat/ChatRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Wednesday, 1 April 2015 12:51:23 o'clock BST
*/

public interface ChatRoomOperations 
{
  void registerCB (Chat.Member m, String name);
  void chat (String c, String name);
  void setChoice (Chat.Member m, int choice);
} // interface ChatRoomOperations
