package Chat;

/**
* Chat/GameRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:34:48 o'clock GMT
*/

public final class GameRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.GameRoom value = null;

  public GameRoomHolder ()
  {
  }

  public GameRoomHolder (Chat.GameRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.GameRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.GameRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.GameRoomHelper.type ();
  }

}
