package Chat;


/**
* Chat/GameRoom_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:34:48 o'clock GMT
*/

public class GameRoom_Tie extends _GameRoomImplBase
{

  // Constructors
  public GameRoom_Tie ()
  {
  }

  public GameRoom_Tie (Chat.GameRoomOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Chat.Member m, String name)
  {
    _impl.registerCB(m, name);
  } // registerCB

  public void chat (String c, String name)
  {
    _impl.chat(c, name);
  } // chat

  public void game (Chat.Member m)
  {
    _impl.game(m);
  } // game

  private Chat.GameRoomOperations _impl;

} // class GameRoom_Tie
