package Chat;


/**
* Chat/GameRoomHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:34:48 o'clock GMT
*/

abstract public class GameRoomHelper
{
  private static String  _id = "IDL:Chat/GameRoom:1.0";

  public static void insert (org.omg.CORBA.Any a, Chat.GameRoom that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Chat.GameRoom extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Chat.GameRoomHelper.id (), "GameRoom");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Chat.GameRoom read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameRoomStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Chat.GameRoom value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Chat.GameRoom narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Chat.GameRoom)
      return (Chat.GameRoom)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Chat._GameRoomStub stub = new Chat._GameRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Chat.GameRoom unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Chat.GameRoom)
      return (Chat.GameRoom)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Chat._GameRoomStub stub = new Chat._GameRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
