package Chat;


/**
* Chat/GameRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:34:48 o'clock GMT
*/

public interface GameRoomOperations 
{
  void registerCB (Chat.Member m, String name);
  void chat (String c, String name);
  void game (Chat.Member m);
} // interface GameRoomOperations
