package Chat;


/**
* Chat/Member.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Tuesday, 31 March 2015 15:22:24 o'clock BST
*/

public interface Member extends MemberOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Member
