package Chat;


/**
* Chat/Member.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Wednesday, 1 April 2015 12:51:23 o'clock BST
*/

public interface Member extends MemberOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Member
