package Chat;


/**
* Chat/Member_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Wednesday, 1 April 2015 12:51:23 o'clock BST
*/

public class Member_Tie extends _MemberImplBase
{

  // Constructors
  public Member_Tie ()
  {
  }

  public Member_Tie (Chat.MemberOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBack (String message)
  {
    _impl.callBack(message);
  } // callBack

  private Chat.MemberOperations _impl;

} // class Member_Tie
