package Chat;


/**
* Chat/Member.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Thursday, 26 March 2015 14:24:26 o'clock GMT
*/

public interface Member extends MemberOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Member
