package Chat;


/**
* Chat/MemberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Distributed systems/Chat/Chatroom.idl
* Wednesday, 18 March 2015 13:38:05 o'clock GMT
*/

public interface MemberOperations 
{
  void callBack (String message);
} // interface MemberOperations
