package Chat;


/**
* Chat/MemberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/Distributed-Systems-Project/Chatroom.idl
* Wednesday, 1 April 2015 12:51:23 o'clock BST
*/

public interface MemberOperations 
{
  void callBack (String message);
} // interface MemberOperations
